
import sangita from "./Bagul Sangitaben Subhashbhai (GNM).jpg"
import puja from "./Bhoya Pujaben Jayeshbhai (GNM).jpg"
import Hitesh from "./Dalvi Hiteshbhai Harichandbhai (GNM).jpg"
import Hemakshi from "./Dhoom Hemakshiben Santabhai (ANM).jpg"
import Anjali from "./Gamit Anjalikumari Ashwinbhai (GNM).jpg"
import Dimpal from "./Gamit Dimpalben Kalanbhai (GNM).jpg"
import Sajnika from "./Gamit Sajnikaben Jashvantbhai (GNM).jpg"
import Anjana from "./Gaykvad Anjanaben Manubhai(ANM).jpg"
import Hira from "./Gaykwad Hiraben Motirambhai(ANM).jpg"
import Amisha from "./Girjali Amishaben Nareshbhai(ANM).jpg"
import Mahema from "./Halpati Mahimaben Dineshbhai (ANM).jpg"
import Lasita from "./Khanjadiya Lasitaben Rashikbhai (GNM).jpg"
import kamini from "./Mahla Kaminiben Jagdishbhai (ANM).jpg"
import Divya from "./Patel Divyakumari Jayeshbhai (GNM).jpg"
import Hinal from "./Patel Hinalben Kishorbhai (ANM).jpg"
// import Mahesesvari from "./Patel Maheshvariben Vijaybhai (GNM).jpg"
// import Poorvi from "./Patel Poorviben Kamleshbhai (GNM).jpg"
// import Rameswari from "./Patel Rameswariben Rohitbhai (ANM).jpg"
// import Sanjna from "./Patel Sanjnaben Bharatbhai (GNM).jpg"
// import Hinal from "./Pawar Hinalben Tulshirambhai (ANM).jpg"
// import Zarina from "./Radiya Zarinaben Satishbhai (GNM).jpg"

export {sangita,puja,Hitesh,Hemakshi,Anjali,Dimpal,Sajnika,Anjana,Hira,Amisha,Mahema,Lasita,kamini,Divya,Hinal}